/**
 * Token access capabilities (scopes).
 * REFERENCE: https://github.com/gravwell/gravwell/blob/dev/client/types/abac.go
 */

enum _Capabilities {
	'Search',
	'Download',
	'SaveSearch',
	'AttachSearch',
	'BackgroundSearch',
	'GetTags',
	'SetSearchGroup',
	'SearchHistory',
	'SearchGroupHistory',
	'SearchAllHistory',
	'DashboardRead',
	'DashboardWrite',
	'ResourceRead',
	'ResourceWrite',
	'TemplateRead',
	'TemplateWrite',
	'PivotRead',
	'PivotWrite',
	'MacroRead',
	'MacroWrite',
	'LibraryRead',
	'LibraryWrite',
	'ExtractorRead',
	'ExtractorWrite',
	'UserFileRead',
	'UserFileWrite',
	'KitRead',
	'KitWrite',
	'KitBuild',
	'KitDownload',
	'ScheduleRead',
	'ScheduleWrite',
	'SOARLibs',
	'SOAREmail',
	'PlaybookRead',
	'PlaybookWrite',
	'LicenseRead',
	'Stats',
	'Ingest',
	'ListUsers',
	'ListGroups',
	'ListGroupMembers',
	'NotificationRead',
	'NotificationWrite',
	'SystemInfoRead',
	'TokenRead',
	'TokenWrite',
}

export type Capabilities = keyof typeof _Capabilities;
